# secret
# 存储敏感信息，用户密码/证书私钥/仓库认证等
# 每个单独的Secret大小不超过1MB，不鼓励大尺寸的secret,会占用大量API Server和kubelet内存
# 使用方式：
# 1. (主要用于API Server鉴权方面)创建Pod时，通过Pod指定ServiceAccountName来自动使用Secret
# 2. 通过挂载Secret到pod使用
# 3. Docker镜像下载时，通过指定Pod的spec.imagePullSecrets来引用
apiVersion: v1
kind: Secret
metadata:
  name: "secret"
  namespace: default
type: "xxx"
data:  # data子域值必须为base64编码值
  key1: value1
  key2: value2
stringData:
  key1: value1
  key2: value2