# serviceAccount
# 账号，提供给运行在Pod里的进程的必要身份证明（而非k8s集群用户，系统管理员，运维人员，租户用户）
#
# 每个namespace下都有一个default默认ServiceAccount对象，里有一个Tokens可以当做Volume被挂载到Pod的Secret。
#  当Pod启动时，Secret自动被挂载到Pod指定目录下(/var/run/secrets/kubernetes.io/serviceaccount)，协助完成Pod中进程访问APIServer时的身份鉴权过程。
#
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "serviceAccount"
  namespace: default
secrets:
  - sercrets1
imagePullSecrets: # 不同于secrets，secrets可安装在pod中，imagePullSecrets只能由kubelet访问
  - name: ""
automountServiceAccountToken: false # 可以在pod层被重写