# Ingress策略定义和一个具体的Ingress Controller结合，形成完整的http负载分发
# Ingress对象定义策略。Ingress Controller(一般使用谷歌nginx-ingress-controller镜像创建daemonSet形式Pod)
# Ingress Controller将根据Ingress的规则设置将客户端请求直接转发到Service后端Endpoint上，跳过kube-proxy设置的iptables规则，kube-proxy不起作用
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  backend: # 用于服务那些没有匹配到任何规则的请求（配置时backend、rules必有其一）
    serviceName: x
    servicePort: x
  rules:  # 定义资源转发列表，rules定义规则，没有匹配到的流量转发到由backend定义默认后端
  - host: x  # 暂不支持IP地址
    http:
      paths:
      - path: x
        backend:
          serviceName: x
          servicePort: x
  tls:
    hosts:
    - xxx
    - xxx
    secretName: x