apiVersion: v1
kind: Pod
metadata:
  labels:
    app: test
  name: test
spec:
  containers:
  - image: busybox:latest
    imagePullPolicy: Never
    name: busybox
    command: ["/bin/sh"]
    args: ["-c","while true;do echo hello;sleep 10;done"]