---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myApp
  strategy: {}
  template:
    metadata:
      labels:
        app: myApp
    spec:
      containers:
      - image: centos:latest
        imagePullPolicy: Never
        name: centos
        command: ["/bin/bash"]
        args:
          - "-c"
          - "while true;do echo helloword;sleep 10;done"
---
# non-selector方式,自定义endpoints,将流量导向到ip:port
kind: Service
apiVersion: v1
metadata:
  name: my-service
  namespace: default
spec:
  type: ClusterIP
  ports:
  - name: test-non-selector
    protocol: TCP
    port: 80
    targetPort: 50075

---
apiVersion: v1
kind: Endpoints
metadata:
  name: my-service
  namespace: default
subsets:
- addresses:
  - ip: 192.168.183.154
  ports:
  - name: test-non-selector   # 若此处指明name值，service也必须指明，否则不生效
    port: 50075
    protocol: TCP